### ISSUE TITLE
Plural minutes when no plural

### ISSUE THREAD

**Issue by Quahu** [Izumemori/Muscord#1]
# Big bad bug
As shown on the screenshot below the issue is quite obnoxious and makes the lib LITERALLY U N U S A B L E. Fix **as soon as possible** (asap in short (ais)).

![khrsamy](https://user-images.githubusercontent.com/24848652/34329347-a453ca3c-e8fc-11e7-91bc-8fdac8ae1262.png)

Some suggestions:
```csharp
$"{(amount > 1 ? "minutes" : "minute")}"
```
or
```csharp
$"minute{(amount > 1 ? "s" : "")}"
```

**Comment by TurboLOL** [comment]
Agreed, fix quick. Its LITERALLY U N U S A B L E

**Comment by Izumemori** [comment]
I don't see how this is an important issue, closing

**Comment by TurboLOL** [comment]
Smh

**Comment by Quahu** [comment]
wtf man

**Comment by Izumemori** [comment]
:^)

**Comment by Izumemori** [comment]
ok, but you have to fix

**Comment by Quahu** [comment]
I don't really have experience with .NET+

**Comment by Izumemori** [comment]
Stop memeing and get to work
